#!/bin/bash


while read oldrev newrev ref
do
	if [[ $ref =~ .*/master$ ]];
	then
		echo "Master ref received. Deploying master branch to production..."
		cd $WORKING_DIR
		unset GIT_DIR
		./scrips/deploy
	fi
done
