#!/bin/bash

WORKING_DIR=~/build
DEPLOYMENT_BRANCH=master

while read oldrev newrev ref
do
	if [[ $ref =~ .*/master$ ]];
	then
		echo "Master ref received. Deploying master branch to production..."
		git --work-tree=/home/hudson/build --git-dir=/home/hudson/textto.js checkout -f

		cd $WORKING_DIR
		npm install
		ember build --environment="production"
		rm -r ~/app
		mkdir ~/app
		cp -a ./dist/. ~/app
	fi
done
